Creating numpy array


In [6]:
## np.array

import numpy as np
a= np.array([1,2,4,5,6,7])
print(a)


[1 2 4 5 6 7]


In [17]:
# // 3d list  and 2D
# Same element hone chahiye no. of
import numpy as np


b = np.array([[1,2,3], [3,4,5], [7,8,3], [2,4,5]]) 
print(b)




[[1 2 3]
 [3 4 5]
 [7 8 3]
 [2 4 5]]


In [ ]:
# //dtye 
import numpy as np

np.array([3,4,5], dtype = float)


array([3., 4., 5.])

In [24]:
# rane

np.arange(12,34)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33])

In [27]:

## with reshape

np.arange(3,7).rephase(3,6)

AttributeError: 'numpy.ndarray' object has no attribute 'rephase'

In [1]:
# Demonstrating Tuples and Lists

# Creating a tuple
my_tuple = (1, 2, 3, 4, 5)
print("Tuple:", my_tuple)

# Creating a list
my_list = [1, 2, 3, 4, 5]
print("List:", my_list)

# Differences between tuples and lists
print("\nDifferences:")

# Immutability of tuples
try:
    my_tuple[0] = 10
except TypeError as e:
    print("Tuples are immutable:", e)

# Mutability of lists
my_list[0] = 10
print("Lists are mutable:", my_list)

# Applications of tuples and lists

# Lists can be used to store homogeneous items
homogeneous_list = [1, 2, 3, 4, 5]
print("\nHomogeneous list:", homogeneous_list)

# Lists can be used to store heterogeneous items
heterogeneous_list = [1, "apple", 3.14, True]
print("Heterogeneous list:", heterogeneous_list)

# Tuples are used for fixed collections of items
coordinates = (10, 20)
print("\nCoordinates (tuple):", coordinates)

# Lists are used for dynamic collections of items
fruits = ["apple", "banana", "cherry"]
print("Fruits (list):", fruits)

# Adding elements to a list
fruits.append("date")
print("List after appending:", fruits)


Tuple: (1, 2, 3, 4, 5)
List: [1, 2, 3, 4, 5]

Differences:
Tuples are immutable: 'tuple' object does not support item assignment
Lists are mutable: [10, 2, 3, 4, 5]

Homogeneous list: [1, 2, 3, 4, 5]
Heterogeneous list: [1, 'apple', 3.14, True]

Coordinates (tuple): (10, 20)
Fruits (list): ['apple', 'banana', 'cherry']
List after appending: ['apple', 'banana', 'cherry', 'date']
